CREATE DATABASE wildlife_tracker;

\c wildlife_tracker;


CREATE TABLE animals(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR,
    type VARCHAR,
    health VARCHAR,
    age VARCHAR
    );
    
CREATE TABLE sightings(
    animalId INTEGER,
    ranger VARCHAR,
    location VARCHAR
    );
    
 
CREATE DATABASE wildlife_tracker_test WITH TEMPLATE wildlife_tracker;
    
